package com.woniu.pojo;
// Generated 2019-12-18 22:41:38 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Level generated by hbm2java
 */
public class Level implements java.io.Serializable {

	private Integer levelId;
	private String levelName;
	private Set clazzs = new HashSet(0);

	public Level() {
	}

	public Level(String levelName, Set clazzs) {
		this.levelName = levelName;
		this.clazzs = clazzs;
	}

	public Integer getLevelId() {
		return this.levelId;
	}

	public void setLevelId(Integer levelId) {
		this.levelId = levelId;
	}

	public String getLevelName() {
		return this.levelName;
	}

	public void setLevelName(String levelName) {
		this.levelName = levelName;
	}

	public Set getClazzs() {
		return this.clazzs;
	}

	public void setClazzs(Set clazzs) {
		this.clazzs = clazzs;
	}

}
