package com.woniu.pojo;
// Generated 2019-12-18 22:41:38 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer userId;
	private String userName;
	private String userPwd;
	private Set clazzs = new HashSet(0);
	private Set userRoles = new HashSet(0);

	public User() {
	}

	public User(String userName, String userPwd) {
		this.userName = userName;
		this.userPwd = userPwd;
	}

	public User(String userName, String userPwd, Set clazzs, Set userRoles) {
		this.userName = userName;
		this.userPwd = userPwd;
		this.clazzs = clazzs;
		this.userRoles = userRoles;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPwd() {
		return this.userPwd;
	}

	public void setUserPwd(String userPwd) {
		this.userPwd = userPwd;
	}

	public Set getClazzs() {
		return this.clazzs;
	}

	public void setClazzs(Set clazzs) {
		this.clazzs = clazzs;
	}

	public Set getUserRoles() {
		return this.userRoles;
	}

	public void setUserRoles(Set userRoles) {
		this.userRoles = userRoles;
	}

}
